$xml = '<?xml version="1.0" encoding="UTF-8"?>'
$xml += '<configuration><system.webServer>'
$xml += '<staticContent>'
$xml += '<remove fileExtension=".js" /><mimeMap fileExtension=".js" mimeType="application/javascript" />'
$xml += '<remove fileExtension=".css" /><mimeMap fileExtension=".css" mimeType="text/css" />'
$xml += '<remove fileExtension=".json" /><mimeMap fileExtension=".json" mimeType="application/json" />'
$xml += '<remove fileExtension=".woff2" /><mimeMap fileExtension=".woff2" mimeType="font/woff2" />'
$xml += '<remove fileExtension=".webp" /><mimeMap fileExtension=".webp" mimeType="image/webp" />'
$xml += '</staticContent>'
$xml += '<rewrite><rules>'
$xml += '<rule name="CSB SPA React Router" stopProcessing="true">'
$xml += '<match url=".*" />'
$xml += '<conditions logicalGrouping="MatchAll">'
$xml += '<add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />'
$xml += '<add input="{REQUEST_FILENAME}" matchType="IsDirectory" negate="true" />'
$xml += '</conditions>'
$xml += '<action type="Rewrite" url="/game/index.html" />'
$xml += '</rule>'
$xml += '</rules></rewrite>'
$xml += '<directoryBrowse enabled="false" />'
$xml += '<httpErrors existingResponse="PassThrough" />'
$xml += '</system.webServer></configuration>'

[System.IO.File]::WriteAllText('C:\inetpub\wwwroot\game\web.config', $xml, [System.Text.Encoding]::UTF8)
Write-Host "Done - web.config created"
